
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

#url: "https://joserc87.github.io"
url: "https://www.josecano.net"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "José Ramón Cano"
title: "{ Jose Cano }"
description: "Blog and website of Jose Cano, blogging mainly for tech. Opinions expressed are mine."
keywords: "jose, cano, personal, developer, software, engineer"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 20
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Give me a fish and I will stop being hungry..."
  - text: "...Give me a challenging problem and I will forget that I was
    hungry."
  - text: "Beautiful code and robust software usually come hand by hand"
  - text: "There is no much fun in easy problems"
  - text: "Never stop learning"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "joserc87"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "August 2012 - Today"
    description: "Wroking as a sowftware engineer in R&D learning something new
        every day"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2005 - December 2011"
    description: "Software engineering studies @ Universidad de Granada"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "joserc87@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Jose Cano is a software engineer with more than 5 years of experience in web development (full stack) as well as PC and Mobile development. Proud geek 🤓 technology enthusiast and coding maniac. Loves challenges and beautiful code. Born in 🇪🇸 but citizen of the world 🌍, living currently in Holland, where he works in an R&D department."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/jcanoyribarren"
  - title: "twitter"
    url: "https://twitter.com/joserc87"
  - title: "github"
    url: "https://github.com/joserc87"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/jeditocat.png"

##################
# GPG on Keybase #
##################

keybase-username: joserc87
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
